-- ROOT ITEM을 찾아라
-- 출력: ITEM_ID, ITEM_NAME
-- 정렬: ITEM_ID (오름차순)

SELECT
    ITEM_INFO.ITEM_ID, 
    ITEM_INFO.ITEM_NAME
FROM ITEM_TREE
JOIN ITEM_INFO
    ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
WHERE ITEM_TREE.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_INFO.ITEM_ID;

