(
SELECT
    SALES_DATE,
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >= '2022-03-01'
  AND SALES_DATE < '2022-04-01'
UNION
SELECT
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d"),
    PRODUCT_ID,
    NULL USER_ID,
    SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >= '2022-03-01'
  AND SALES_DATE < '2022-04-01'
)
ORDER BY
    SALES_DATE,
    PRODUCT_ID,
    USER_ID;
