WITH ECOLI_DATA_RANK_LIST AS (
    SELECT
        ID,
        SIZE_OF_COLONY,
        100.0 * PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS 'PERCENTILE'
    FROM ECOLI_DATA
)

SELECT
    ID,
    CASE
        WHEN PERCENTILE <= 25 THEN 'CRITICAL'
        WHEN PERCENTILE <= 50 THEN 'HIGH'
        WHEN PERCENTILE <= 75 THEN 'MEDIUM'
        ELSE 'LOW' 
    END AS COLONY_NAME
FROM ECOLI_DATA_RANK_LIST
ORDER BY ID;
