WITH user_list AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID) * 1.0 / (SELECT COUNT(*) FROM user_list), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS os
INNER JOIN user_list AS ul 
    ON os.USER_ID = ul.USER_ID
GROUP BY 
    YEAR,
    MONTH
ORDER BY 
    YEAR, 
    MONTH;