SELECT
    FOOD_ORDER.PRODUCT_ID,
    FOOD_PRODUCT.PRODUCT_NAME,
    SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER
INNER JOIN FOOD_PRODUCT
    ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE SUBSTRING(FOOD_ORDER.PRODUCE_DATE, 1, 7) = '2022-05'
GROUP BY
    FOOD_ORDER.PRODUCT_ID,
    FOOD_PRODUCT.PRODUCT_NAME
ORDER BY 
    SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) DESC,
    FOOD_ORDER.PRODUCT_ID;
